// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniCourseCatalog.Mvc.Data;

#nullable disable

namespace MiniCourseCatalog.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609033400_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentEnrollment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TuitionFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseCategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PRG-201",
                            CourseCategoryId = 1,
                            CurrentEnrollment = 28,
                            Instructor = "Cô Lê Thị Hoa",
                            MaxCapacity = 30,
                            Name = "Lập Trình Hướng Đối Tượng C#",
                            StartDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TuitionFee = 2500000m
                        },
                        new
                        {
                            Id = 2,
                            Code = "DATA-302",
                            CourseCategoryId = 2,
                            CurrentEnrollment = 9,
                            Instructor = "Thầy Trần Đức Hùng",
                            MaxCapacity = 25,
                            Name = "Nhập môn Khoa Học Dữ Liệu",
                            StartDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TuitionFee = 3500000m
                        },
                        new
                        {
                            Id = 3,
                            Code = "ENG-105",
                            CourseCategoryId = 3,
                            CurrentEnrollment = 5,
                            Instructor = "Ms. Emily Smith",
                            MaxCapacity = 20,
                            Name = "Tiếng Anh Giao Tiếp VSTEP B1",
                            StartDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TuitionFee = 1800000m
                        },
                        new
                        {
                            Id = 4,
                            Code = "DIG-101",
                            CourseCategoryId = 4,
                            CurrentEnrollment = 8,
                            Instructor = "Cô Trần Thanh Mai",
                            MaxCapacity = 30,
                            Name = "Digital Marketing Cơ Bản",
                            StartDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TuitionFee = 2000000m
                        });
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.CourseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CourseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các khóa học về lập trình, phần mềm và hệ thống máy tính",
                            Name = "Công nghệ Thông tin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Các khóa học về trí tuệ nhân tạo và khoa học dữ liệu",
                            Name = "AI & Data Science"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Các khóa học ngôn ngữ quốc tế",
                            Name = "Ngoại Ngữ"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Các khóa học về tiếp thị và kinh doanh số",
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "an.nguyen@example.com",
                            FullName = "Nguyễn Văn An",
                            PhoneNumber = "0901234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bich.tran@example.com",
                            FullName = "Trần Thị Bích",
                            PhoneNumber = "0912345678"
                        });
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Course", b =>
                {
                    b.HasOne("MiniCourseCatalog.Mvc.Models.CourseCategory", "CourseCategory")
                        .WithMany("Courses")
                        .HasForeignKey("CourseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseCategory");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Enrollment", b =>
                {
                    b.HasOne("MiniCourseCatalog.Mvc.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCourseCatalog.Mvc.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.CourseCategory", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("MiniCourseCatalog.Mvc.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
